# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1233419418bcdb9776819b55361569dcb84c207f6bf1c270def244743f0db64463e792fb441a1094015b0f2cfa8f9b96a9167846dabb6c099f842b6e9d708dd4

test:
  secret_key_base: 29806206f03081b85271edc8af535900951ca914e0ba53914c50fc960e26c3d47b92b00f0f4f2479266d8cc4624e2a7ef18916b5c0f19e2d9c5ab8e93eec2aa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
